export const GET_EYEGLASSES_LOADING = "GET_EYEGLASSES_LOADING"
export const GET_EYEGLASSES_ERROR = "GET_EYEGLASSES_ERROR"
export const GET_EYEGLASSES_SUCCESS = "GET_EYEGLASSES_SUCCESS"

export const GET_SUNGLASSES_LOADING = "GET_SUNGLASSES_LOADING"
export const GET_SUNGLASSES_ERROR = "GET_SUNGLASSES_ERROR"
export const GET_SUNGLASSES_SUCCESS = "GET_SUNGLASSES_SUCCESS"

export const GET_COMPUTERGLASSES_LOADING = "GET_COMPUTERGLASSES_LOADING"
export const GET_COMPUTERGLASSES_ERROR = "GET_COMPUTERGLASSES_ERROR"
export const GET_COMPUTERGLASSES_SUCCESS = "GET_COMPUTERGLASSES_SUCCESS"

