export const POST_USER_DATA_LOADING = "POST_USER_DATA_LOADING"
export const POST_USER_DATA_ERROR = "POST_USER_DATA_ERROR"
export const POST_USER_DATA_SUCCESS = "POST_USER_DATA_SUCCESS"

export const GET_USER_DATA_LOADING = "GET_USER_DATA_LOADING"
export const GET_USER_DATA_ERROR = "GET_USER_DATA_ERROR"
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS"

export const LOGOUT_USER_DATA_LOADING = "LOGOUT_USER_DATA_LOADING"
export const LOGOUT_USER_DATA_ERROR = "LOGOUT_USER_DATA_ERROR"
export const LOGOUT_USER_DATA_SUCCESS = "LOGOUT_USER_DATA_SUCCESS"
