export const GET_WISHLIST_REQUEST = 'GET_WISHLIST_REQUEST';
export const GET_WISHLIST_SUCCESS = 'GET_WISHLIST_SUCCESS';
export const GET_WISHLIST_FAILURE = 'GET_WISHLIST_FAILURE';


export const POST_WISHLIST_SUCCESS = 'POST_WISHLIST_SUCCESS';
//export const POST_WISHLIST_FAILURE = 'POST_WISHLIST_FAILURE';
